[package]
name = "lzn"
version = "0.1.0"
authors = ["Nam Jeonghyun <ska827@snu.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22"
glob = "0.3"
structopt = { version = "0.3", default-features = false }

[profile.release]
# debug = true
panic = "abort"

